### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by N7Remus** [N7Remus/fcm-reduction#1]
- [x] Implement multithreaded app for reduction clustering 
- [x] Implement API for data communication 
- [ ] Implement multithreaded app for creating modified modell based on reduction clustering
- [ ] Implement UI to visualize the reduced modell
- [x] Implement import/export functionality
- [ ] Implement UI for database modification
- [ ] Implement Simulation for large modells
- [ ] Finish interactive UI
- [ ] Finish interactive table manipulation
- [ ] Implement pooling worker host(s)
- [ ] Hunt bugs
![image](https://github.com/N7Remus/fcm-reduction/assets/18115809/36c6dee7-d9b9-47d0-9f1a-a128446b05b7)
